# Generated by Django 6.1 on 2026-08-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_slug_product_is_new_product_is_sale_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
