# Generated by Django 6.1 on 2026-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
