# Generated by Django 6.1 on 2026-08-16 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_review_review_comment_review_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimum_stock",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
