# Generated by Django 6.1 on 2026-08-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_product_minimum_stock_alter_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="minimum_stock",
            new_name="low_stock_limit",
        ),
    ]
