# Generated by Django 6.1 on 2026-08-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_cart_session_key_alter_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="e.g. bi-cup-hot, bi-bag",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text",
            field=models.CharField(
                default="Fast Delivery All Across Pakistan!", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="is_announcement_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(default="+92 322 3489220", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(default="923223489220", max_length=20),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="store.subcategory",
            ),
        ),
    ]
