# Generated by Django 6.1 on 2026-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_cart_user_wishlist_user_alter_cart_session_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="My E-Commerce Store", max_length=150),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Quality Products at Your Doorstep",
                        max_length=200,
                    ),
                ),
                ("phone", models.CharField(default="0300-1234567", max_length=20)),
                (
                    "email",
                    models.EmailField(default="support@store.com", max_length=254),
                ),
                ("address", models.TextField(default="Karachi, Pakistan")),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_title", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                (
                    "invoice_footer",
                    models.TextField(
                        default="Thank you for shopping with us! No return after 7 days."
                    ),
                ),
            ],
        ),
    ]
