# Generated by Django 6.1 on 2026-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_storesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
