# Generated by Django 6.1 on 2026-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_order_gateway_response_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account_title",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_iban",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
