# Generated by Django 6.1 on 2026-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_purchase_supplier_purchaseitem_purchase_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="courier_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatch_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="PurchaseItem",
        ),
    ]
