# Generated by Django 6.1 on 2026-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_productreturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="delivery_charges",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="opening_hours",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
