# Generated by Django 6.1 on 2026-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("announcement", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="StoreSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="store/")),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=200)),
                (
                    "delivery_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
