"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config as env_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x&4fef-3im#d&mm$!!zf&#86@o96$!oe$e277&syi5-ua50s+i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
     "dashboard",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "store.context_processors.global_data",
                "store.context_processors.navbar_counts",
            ],
        },
    },
]
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "MaryamCrockeryDB",
        "HOST": r".\MSSQLSERVER01",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "trusted_connection": "yes",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/


STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "arfahanif2812@gmail.com"
EMAIL_HOST_PASSWORD = "arfam1234567890"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ==========================================
# PAYMENT GATEWAY CREDENTIALS (from .env)
# ==========================================

JAZZCASH_MERCHANT_ID = env_config("JAZZCASH_MERCHANT_ID", default="")
JAZZCASH_PASSWORD = env_config("JAZZCASH_PASSWORD", default="")
JAZZCASH_INTEGRITY_SALT = env_config("JAZZCASH_INTEGRITY_SALT", default="")
JAZZCASH_RETURN_URL = env_config("JAZZCASH_RETURN_URL", default="http://127.0.0.1:8000/payment/jazzcash/callback/")
JAZZCASH_POST_URL = env_config(
    "JAZZCASH_POST_URL",
    default="https://sandbox.jazzcash.com.pk/CustomerPortal/transactionmanagement/merchantform/",
)

EASYPAISA_STORE_ID = env_config("EASYPAISA_STORE_ID", default="")
EASYPAISA_HASH_KEY = env_config("EASYPAISA_HASH_KEY", default="")
EASYPAISA_RETURN_URL = env_config("EASYPAISA_RETURN_URL", default="http://127.0.0.1:8000/payment/easypaisa/callback/")
EASYPAISA_POST_URL = env_config(
    "EASYPAISA_POST_URL",
    default="https://easypaystg.easypaisa.com.pk/easypay/Index.jsf",
)